kind: Deployment
apiVersion: apps/v1
metadata:
  name: opendora
  namespace: opendora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opendora
  template:
    metadata:
      labels:
        app: opendora
    spec:
      containers:
        - name: container
          image: 'quay.io/suchugh/dora-api-mock:0.0.1-SNAPSHOT'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

